### ISSUE TITLE
AttributeError: 'types.SimpleNamespace' object has no attribute 'bands'

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/neuropacks#11]
When running `tonemap.ipynb`, I run into this error with an attributeerror on a pack object.

This line fails:
`wrapper_tonemap_figure(nwb_path, device='ECoG', figsize=(12, 8))`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5679/4047926929.py in <module>
      1 # (step 1) extract data using neuropack
      2 device = 'ECoG'
----> 3 pack, design, responses, frq_set, amp_set = extract_tone_responses(
      4     nwb_path, device=device, fmin=70, fmax=170, in_memory=True)
      5 

~/software/pyraat/pyraat/tone/tonemap_figure.py in extract_tone_responses(nwb_path, device, pack, fmin, fmax, in_memory)
     64     # select bands within the frequency range
     65     proc_summary = pack._get_processed_neural_data(device, load_data=False)
---> 66     cfs = proc_summary.bands['band_mean'].to_numpy()    # center frequencies
     67     band_idx = np.logical_and(cfs >= fmin, cfs <= fmax)
     68 

AttributeError: 'types.SimpleNamespace' object has no attribute 'bands'

**Comment by jihyunbak** [comment]
Hi @jthermiz , saw this real time 😎 you can check out my branch `dev-tonemap-analysis`!

**Comment by jthermiz** [comment]
Yay it works now! Thanks @jihyunbak !

**Comment by jihyunbak** [comment]
Closed by #12
